site_name: DocumentaciÃ³n de Javi
remote_branch: gh-deploy
theme: readthedocs
nav:
- Home: index.md
- CLI tools:
  - ğŸ“ Dirs (cd,ls,find,ranger):   cli_tools/1_dirs.md
  - ğŸ“„ Files (cat,file,stat):      cli_tools/2_files.md
  - â³ Process (ps,top):           cli_tools/3_process.md
  - ğŸ—œï¸ Compress (zip,tar,bz):      cli_tools/compression.md
  - ğŸ”‘ Cryptography (base64):      cli_tools/cryptography.md
  - ğŸ“Š Plotting (gnuplot):         cli_tools/plotting.md
  - ğŸ‘¨â€ğŸ’» Scripting:                  cli_tools/scripting.md
  - ğŸ¨ Customization (dotfiles):   cli_tools/customization.md
  - GIT:                           cli_tools/git.md
  - ğŸ“ Editors (nano,vim,jupyter): cli_tools/editors.md
  - ğŸ“¦ Software (pacman,aur,pip):  cli_tools/pacman.md
  - SSH:                           cli_tools/ssh.md
  - TMUX:                          cli_tools/tmux.md
- CLI data tools:
  - âšªï¸ Free text (regex,grep,tr,sed):  cli_tools_data/free_text.md
  - ğŸŸ¢ Excel,csv,tsv (cut,paste,awk):  cli_tools_data/csv.md
  - ğŸŸ¡ HTML (pup) XML:                 cli_tools_data/html.md
  - ğŸŸ  JSON (jq):                      cli_tools_data/json.md
  - ğŸ”´ PDF (Xpdf,poppler):             cli_tools_data/pdf.md
  - ğŸ”µ Image (ImageMagick):            cli_tools_data/image.md
  - ğŸŸ£ Sound,Video (ffmepg,sox):       cli_tools_data/sound_video.md
- CLI networking tools:
  - â¬‡ï¸ Web Scraping (curl,wget): cli_tools_net/web_scraping.md
  - ğŸ—¡ï¸ Pentesting (nmap):        cli_tools_net/pentesting.md
  - ğŸ›¡ï¸ Deffensive:               cli_tools_net/deffensive.md
  - ğŸ“’ DNS (dig,nslookup,whois): cli_tools_net/dns.md
  - ğŸ”’ VPN:                      cli_tools_net/vpn.md
  - ğŸ“› Firewall:                 cli_tools_net/firewall.md
- Python:
  - ğŸŸ¦ Numpy:      python/numpy.md
  - ğŸŸ« Sklearn:    python/machine_learning.md
  - ğŸŸ¥ Pytorch:    python/pytorch.md
  - ğŸŸ§ Tensorflow: python/tensorflow.md
  - â¬œï¸ ONNX:       python/onnx.md
  - ğŸŸ© TensorRT:   python/tensorrt.md
  - ğŸŸ¦ Parallel:   python/numpy.md
- C++:
  - â™¦ï¸ Ruby:    programming/ruby.md
  - Monitoring: programming/monitoring.md
  - Profiling:  programming/profiling.md
  - Debugging:  programming/debugging.md
  - Makefile:   programming/makefile.md


