site_name: DocumentaciÃ³n de Javi
remote_branch: gh-deploy
theme: readthedocs
nav:
- Home: index.md
- CLI tools:
  - Bash:    tools/bash.md
  - GIT:     tools/git.md
  - Jupyter: tools/jupyter.md
  - Nano:    tools/nano.md
  - Pacman:  tools/pacman.md
  - SSH:     tools/ssh.md
  - TMUX:    tools/tmux.md
  - Vim:     tools/vim.md
  - ZSH:     tools/bash.md
- CLI data tools:
  - âšªï¸ FREE TEXT (regex):  tools_data/free_text.md
  - ğŸŸ¢ Excel,CSV,TSV (cut, paste, tr, sed, awk): tools_data/csv.md
  - ğŸŸ¡ HTML (pup):          tools_data/html.md
  - ğŸŸ  JSON (jq):           tools_data/json.md
  - ğŸ”´ PDF (Xpdf, poppler): tools_data/pdf.md
  - ğŸ”µ Image (ImageMagick): tools_data/image.md
  - ğŸŸ£ Sound,Video (ffmepg, sox): tools_data/sound_video.md
- Software 1.0:
  - Bash:       programming/bash.md
  - Python:     programming/python.md
  - â™¦ï¸ Ruby:    programming/ruby.md
  - Monitoring: programming/monitoring.md
  - Profiling:  programming/profiling.md
  - Debugging:  programming/debugging.md
  - Makefile:   programming/makefile.md
- Software 2.0:
  - ğŸŸ¦ Numpy:      ai/numpy.md
  - ğŸŸ« Sklearn:    ai/machine_learning.md
  - ğŸŸ¥ Pytorch:    ai/pytorch.md
  - ğŸŸ§ Tensorflow: ai/tensorflow.md
  - â¬œï¸ ONNX:       ai/onnx.md
  - ğŸŸ© TensorRT:   ai/tensorrt.md
- Others:
  - â³ Process:      others/process.md
  - ğŸ”‘ Cryptography: others/cryptography.md
  - Linux insides:   others/linux_insides.md
  - ğŸ–¥ï¸ Remote admin: others/remote_administration.md
  - â¬‡ï¸ Web Scraping (curl, wget): others/web_scraping.md
  - ğŸ—¡ï¸ Pentesting (nmap): others/pentesting.md
  - ğŸ›¡ï¸ Deffensive:   others/deffensive.md
  - DNS (dig, nslookup, whois): others/dns.md
  - VPN: others/vpn.md
  - ğŸ“› Firewall: others/firewall.md
  - ğŸ“¦ Packets (wireshark): others/packets.md
  - Load balancer: others/load_balancer.md
  - Public IP:     others/public_ip.md


