site_name: DocumentaciÃ³n de Javi
remote_branch: gh-deploy
theme: readthedocs
nav:
- Home: index.md
- Linux:
  - Bash fundamentals (cd, ls, ...): tools/bash_basics.md
  - Bash scripting: tools/bash_scripting.md
  - Process: tools/process.md
  - ğŸ“ Editors (nano, vim, jupyter): tools/editors.md
  - ğŸ› ï¸ Install software (pacman, pip, conda): tools/install.md
  - ğŸ”‘ Cryptography: tools/cryptography.md
  - GIT: tools/git.md
  - Linux insides: linux_insides.md
  - Hardware: hardware.md
- Data tools:
  - âšªï¸ TEXT,CSV (cut, paste, tr, sed, awk): tools_data/text.md
  - ğŸŸ¡ HTML (pup): tools_data/html.md
  - ğŸŸ  JSON (jq): tools_data/json.md
  - ğŸ”´ PDF (Xpdf, poppler): tools_data/pdf.md
  - ğŸ”µ Image (ImageMagick): tools_data/image.md
  - ğŸŸ¢ Sound,Video (ffmepg, sox): tools_data/sound_video.md
- AI:
  - ğŸ”³ Machine Learning (skit-learn): ai/machine_learning.md
  - ğŸ”² Deep Learning (pytorch): ai/deep_learning.md
- Networking:
  - ğŸ–¥ï¸ Remote administration (ssh, tmux, wakeonlan): networking/ssh.md
  - â¬‡ï¸ Web Scraping (curl, wget): networking/web_scraping.md
  - ğŸ—¡ï¸ Pentesting (nmap): networking/pentesting.md
  - ğŸ›¡ï¸ Deffensive: networking/deffensive.md
  - DNS (dig, nslookup, whois): networking/dns.md
  - ğŸ“› Firewall: networking/firewall.md
  - ğŸ“¦ Packets (wireshark): networking/packets.md
  - Load balancer: networking/load_balancer.md
  - Public IP: networking/public_ip.md
- Programming:
  - Monitoring: programming/monitoring.md
  - Profiling:  programming/profiling.md
  - Debugging:  programming/debugging.md
  - Makefile:   programming/makefile.md


