site_name: Documentaci√≥n de Javi
remote_branch: gh-deploy
theme: readthedocs
nav:
- Home: index.md
- Linux tools:
  - Bash fundamentals (cd, ls, ...): tools/bash_basics.md
  - Bash scripting: tools/bash_scripting.md
  - Editors (nano, vim, jupyter): tools/editors.md
  - üõ†Ô∏è Install software (pacman, pip, conda): tools/install.md
  - ‚¨áÔ∏è Download data (curl, wget, youtube-dl): tools/downloaders.md
  - GIT: tools/git.md
  - TMUX: tools/tmux.md
  - GNU parallel: tools/gnu_parallel.md
  - SSH: tools/ssh.md
- Data tools:
  - TEXT,CVS,TSV (cut, paste, tr, sed, awk): tools_data/text.md
  - HTML (pup): tools_data/html.md
  - JSON (jq): tools_data/json.md
  - PDF (Xpdf, poppler): tools_data/pdf.md
  - Image (ImageMagick): tools_data/image.md
  - üîà Sound (ffmepg, sox): tools_data/sound.md
  - Video (ffmepg): tools_data/video.md
  - Web Scraping: tools_data/web_scraping.md
- AI:
  - Deep Learning: ai/deep_learning.md
- Programming:
  - Monitoring: programming/monitoring.md
  - Profiling:  programming/profiling.md
  - Debugging:  programming/debugging.md
  - Makefile:   programming/makefile.md
- Server:
  - Wakeonlan: server/wakeonlan.md
  - Firewall: server/firewall.md
  - Load balancer: server/load_balancer.md
  - Public IP: server/public_ip.md
  - Security: server/security.md
- Hardware: hardware.md
- Linux insides: linux_insides.md
