site_name: DocumentaciÃ³n de Javi
remote_branch: gh-deploy
theme: readthedocs
nav:
- Home: index.md
- Linux:
  - Bash fundamentals (cd, ls, ...): tools/bash_basics.md
  - Bash scripting: tools/bash_scripting.md
  - Process: tools/process.md
  - ğŸ“ Editors (nano, vim, jupyter): tools/editors.md
  - ğŸ› ï¸ Install software (pacman, pip, conda): tools/install.md
  - â¬‡ï¸ Web Scraping (curl, wget, api): tools/web_scraping.md
  - ğŸ”‘ Cryptography: tools/cryptography.md
  - GIT: tools/git.md
  - TMUX: tools/tmux.md
  - GNU parallel: tools/gnu_parallel.md
  - SSH: tools/ssh.md
- Data tools:
  - âšªï¸ TEXT,CSV (cut, paste, tr, sed, awk): tools_data/text.md
  - ğŸŸ¡ HTML (pup): tools_data/html.md
  - ğŸŸ  JSON (jq): tools_data/json.md
  - ğŸ”´ PDF (Xpdf, poppler): tools_data/pdf.md
  - ğŸ”µ Image (ImageMagick): tools_data/image.md
  - ğŸŸ¢ Sound,Video (ffmepg, sox): tools_data/sound_video.md
- AI:
  - Deep Learning: ai/deep_learning.md
- Cybersecurity:
  - ğŸ—¡ï¸ Pentesting: cybersecurity/pentesting.md
  - ğŸ›¡ï¸ Deffensive: cybersecurity/deffensive.md
- Programming:
  - Monitoring: programming/monitoring.md
  - Profiling:  programming/profiling.md
  - Debugging:  programming/debugging.md
  - Makefile:   programming/makefile.md
- Server:
  - Wakeonlan: server/wakeonlan.md
  - Firewall: server/firewall.md
  - Load balancer: server/load_balancer.md
  - Public IP: server/public_ip.md

- Hardware: hardware.md
- Linux insides: linux_insides.md
